version: '3.4'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest 

  mymicroservice:
    image: ${DOCKER_REGISTRY-}mymicroservice
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - sqldata